# **Student Score Analysis**

In [ ]:
# 1. Import NumPy
import numpy as np

In [ ]:
# 2. Create data (scores of 5 students)
scores = np.array([65, 70, 75, 80, 85])

print("Student Scores:")
print(scores)

Student Scores:
[65 70 75 80 85]


In [ ]:
# 3. Check number of values
print("\nNumber of scores:", scores.shape)


Number of scores: (5,)


In [ ]:
# 4. Access one value (first student score)
print("\nFirst student score:", scores[3])


First student score: 80


In [ ]:
# 5. Select multiple values (student 2 to student 4)
print("\nScores from student 2 to 4:", scores[1:4])


Scores from student 2 to 4: [70 75 80]


In [ ]:
# 6. Add 5 bonus marks to each student
new_scores = scores + 5
print("\nScores after adding 5 bonus marks:")
print(new_scores)


Scores after adding 5 bonus marks:
[70 75 80 85 90]


In [ ]:
# 7. Calculate statistics
print("\nAverage score:", np.mean(scores))
print("Highest score:", np.max(scores))
print("Lowest score:", np.min(scores))
print("Total score:", np.sum(scores))


Average score: 75.0
Highest score: 85
Lowest score: 65
Total score: 375


In [ ]:
# 8. Compare each score with pass mark (50)
pass_mark = 50
difference = scores - pass_mark

print("\nDifference from pass mark:")
print(difference)


Difference from pass mark:
[15 20 25 30 35]


In [ ]:
# 9. Generate random scores (example practice data)
random_scores = np.random.randint(50, 100, size=5)

print("\nRandom practice scores:")
print(random_scores)


Random practice scores:
[66 80 52 57 81]
